name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terraform-ci:
    name: Terraform CI (fmt + validate)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform fmt
        run: terraform fmt -check -recursive || true

      - name: Terraform init (no backend)
        working-directory: terraform/envs/dev
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: terraform/envs/dev
        run: terraform validate

  deploy-dev:
    name: Terraform Deploy DEV
    runs-on: ubuntu-latest
    needs: terraform-ci
    if: github.ref == 'refs/heads/dev'

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform init (DEV)
        working-directory: terraform/envs/dev
        run: terraform init -reconfigure

      - name: Terraform apply (DEV)
        working-directory: terraform/envs/dev
        run: terraform apply -auto-approve

  deploy-prod:
    name: Terraform Deploy PROD
    runs-on: ubuntu-latest
    needs: terraform-ci
    if: github.ref == 'refs/heads/main'

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform init (PROD)
        working-directory: terraform/envs/prod
        run: terraform init -reconfigure

      - name: Terraform apply (PROD)
        working-directory: terraform/envs/prod
        run: terraform apply -auto-approve
