name: Terraform CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev, main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  # ===============================
  # CI: FMT + VALIDATE (DEV CODE)
  # ===============================
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (DEV)
        working-directory: terraform/envs/dev
        run: terraform init -reconfigure

      - name: Terraform validate (DEV)
        working-directory: terraform/envs/dev
        run: terraform validate

  # ===============================
  # DEPLOY DEV (AUTO)
  # ===============================
  deploy-dev:
    runs-on: ubuntu-latest
    needs: terraform-ci
    if: github.ref == 'refs/heads/dev'

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform apply (DEV)
        working-directory: terraform/envs/dev
        run: terraform apply -auto-approve

  # ===============================
  # DEPLOY PROD (PR â†’ MAIN)
  # ===============================
  deploy-prod:
    runs-on: ubuntu-latest
    needs: terraform-ci
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform apply (PROD)
        working-directory: terraform/envs/prod
        run: terraform apply
