name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terraform-ci:
    name: Terraform FMT + Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      # ------------ FORMAT CHECK ------------
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # ------------ VALIDATION ------------
      - name: Terraform Init (Dev)
        working-directory: terraform/envs/dev
        run: terraform init -backend=false

      - name: Terraform Validate (Dev)
        working-directory: terraform/envs/dev
        run: terraform validate


  # ======================================
  #   DEPLOY DEV ENVIRONMENT
  # ======================================
  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    needs: terraform-ci
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform Init (DEV)
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Apply (DEV)
        working-directory: terraform/envs/dev
        run: terraform apply -auto-approve


  # ======================================
  #   DEPLOY PROD ENVIRONMENT
  # ======================================
  deploy-prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    needs: terraform-ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform Init (PROD)
        working-directory: terraform/envs/prod
        run: terraform init

      - name: Terraform Apply (PROD)
        working-directory: terraform/envs/prod
        run: terraform apply -auto-approve

        